# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import protocolimpls.render_pb2 as render__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in render_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RenderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetJob = channel.unary_unary(
                '/render.RenderService/GetJob',
                request_serializer=render__pb2.GetJobRequest.SerializeToString,
                response_deserializer=render__pb2.GetJobResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/render.RenderService/Heartbeat',
                request_serializer=render__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=render__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.JobComplete = channel.unary_unary(
                '/render.RenderService/JobComplete',
                request_serializer=render__pb2.JobCompleteRequest.SerializeToString,
                response_deserializer=render__pb2.JobCompleteResponse.FromString,
                _registered_method=True)
        self.GrabScene = channel.unary_unary(
                '/render.RenderService/GrabScene',
                request_serializer=render__pb2.GetCurrentSceneRequest.SerializeToString,
                response_deserializer=render__pb2.GetCurrentSceneResponse.FromString,
                _registered_method=True)


class RenderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JobComplete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GrabScene(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RenderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJob,
                    request_deserializer=render__pb2.GetJobRequest.FromString,
                    response_serializer=render__pb2.GetJobResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=render__pb2.HeartbeatRequest.FromString,
                    response_serializer=render__pb2.HeartbeatResponse.SerializeToString,
            ),
            'JobComplete': grpc.unary_unary_rpc_method_handler(
                    servicer.JobComplete,
                    request_deserializer=render__pb2.JobCompleteRequest.FromString,
                    response_serializer=render__pb2.JobCompleteResponse.SerializeToString,
            ),
            'GrabScene': grpc.unary_unary_rpc_method_handler(
                    servicer.GrabScene,
                    request_deserializer=render__pb2.GetCurrentSceneRequest.FromString,
                    response_serializer=render__pb2.GetCurrentSceneResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'render.RenderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('render.RenderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RenderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/render.RenderService/GetJob',
            render__pb2.GetJobRequest.SerializeToString,
            render__pb2.GetJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/render.RenderService/Heartbeat',
            render__pb2.HeartbeatRequest.SerializeToString,
            render__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JobComplete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/render.RenderService/JobComplete',
            render__pb2.JobCompleteRequest.SerializeToString,
            render__pb2.JobCompleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GrabScene(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/render.RenderService/GrabScene',
            render__pb2.GetCurrentSceneRequest.SerializeToString,
            render__pb2.GetCurrentSceneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
