# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: render.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'render.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0crender.proto\x12\x06render\"#\n\rGetJobRequest\x12\x12\n\nproject_id\x18\x01 \x01(\x03\"\x18\n\x16GetCurrentSceneRequest\"-\n\x17GetCurrentSceneResponse\x12\x12\n\nscene_data\x18\x01 \x01(\x0c\"\"\n\nCoordinate\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\"\\\n\tRectangle\x12&\n\nlower_left\x18\x01 \x01(\x0b\x32\x12.render.Coordinate\x12\'\n\x0bupper_right\x18\x02 \x01(\x0b\x32\x12.render.Coordinate\"X\n\x0eGetJobResponse\x12\x36\n\x1bimage_coordinates_to_render\x18\x01 \x01(\x0b\x32\x11.render.Rectangle\x12\x0e\n\x06job_id\x18\x02 \x01(\x03\"\x12\n\x10HeartbeatRequest\"\"\n\x11HeartbeatResponse\x12\r\n\x05\x61live\x18\x01 \x01(\x08\"F\n\x15\x43omputationStatistics\x12\x14\n\x0ctime_seconds\x18\x01 \x01(\x01\x12\x17\n\x0fpixels_rendered\x18\x02 \x01(\x03\"h\n\x12JobCompleteRequest\x12\x14\n\x0crender_chunk\x18\x01 \x01(\x0c\x12\x0e\n\x06job_id\x18\x02 \x01(\x03\x12,\n\x05stats\x18\x03 \x01(\x0b\x32\x1d.render.ComputationStatistics\"+\n\x13JobCompleteResponse\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\x32\xa0\x02\n\rRenderService\x12\x37\n\x06GetJob\x12\x15.render.GetJobRequest\x1a\x16.render.GetJobResponse\x12@\n\tHeartbeat\x12\x18.render.HeartbeatRequest\x1a\x19.render.HeartbeatResponse\x12\x46\n\x0bJobComplete\x12\x1a.render.JobCompleteRequest\x1a\x1b.render.JobCompleteResponse\x12L\n\tGrabScene\x12\x1e.render.GetCurrentSceneRequest\x1a\x1f.render.GetCurrentSceneResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'render_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETJOBREQUEST']._serialized_start=24
  _globals['_GETJOBREQUEST']._serialized_end=59
  _globals['_GETCURRENTSCENEREQUEST']._serialized_start=61
  _globals['_GETCURRENTSCENEREQUEST']._serialized_end=85
  _globals['_GETCURRENTSCENERESPONSE']._serialized_start=87
  _globals['_GETCURRENTSCENERESPONSE']._serialized_end=132
  _globals['_COORDINATE']._serialized_start=134
  _globals['_COORDINATE']._serialized_end=168
  _globals['_RECTANGLE']._serialized_start=170
  _globals['_RECTANGLE']._serialized_end=262
  _globals['_GETJOBRESPONSE']._serialized_start=264
  _globals['_GETJOBRESPONSE']._serialized_end=352
  _globals['_HEARTBEATREQUEST']._serialized_start=354
  _globals['_HEARTBEATREQUEST']._serialized_end=372
  _globals['_HEARTBEATRESPONSE']._serialized_start=374
  _globals['_HEARTBEATRESPONSE']._serialized_end=408
  _globals['_COMPUTATIONSTATISTICS']._serialized_start=410
  _globals['_COMPUTATIONSTATISTICS']._serialized_end=480
  _globals['_JOBCOMPLETEREQUEST']._serialized_start=482
  _globals['_JOBCOMPLETEREQUEST']._serialized_end=586
  _globals['_JOBCOMPLETERESPONSE']._serialized_start=588
  _globals['_JOBCOMPLETERESPONSE']._serialized_end=631
  _globals['_RENDERSERVICE']._serialized_start=634
  _globals['_RENDERSERVICE']._serialized_end=922
# @@protoc_insertion_point(module_scope)
